"""add image_url to player

Revision ID: 1fad7adb62dd
Revises: 24f3a37bedf2
Create Date: 2025-06-26 13:47:55.318581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fad7adb62dd'
down_revision: Union[str, Sequence[str], None] = '24f3a37bedf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'image_url')
    # ### end Alembic commands ###
