"""add debut_date to player

Revision ID: 1ffbb910b300
Revises: d97e42dc5d82
Create Date: 2025-06-27 13:54:05.734068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ffbb910b300'
down_revision: Union[str, Sequence[str], None] = 'd97e42dc5d82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('debut_date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'debut_date')
    # ### end Alembic commands ###
