"""add level to player

Revision ID: d97e42dc5d82
Revises: 1fad7adb62dd
Create Date: 2025-06-26 15:08:41.639126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd97e42dc5d82'
down_revision: Union[str, Sequence[str], None] = '1fad7adb62dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('level', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'level')
    # ### end Alembic commands ###
