"""drop unused tables

Revision ID: f2435961f991
Revises: ef428275ea5f
Create Date: 2025-07-07 15:49:08.005347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2435961f991'
down_revision: Union[str, Sequence[str], None] = 'ef428275ea5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TABLE IF EXISTS atbats CASCADE')
    op.execute('DROP TABLE IF EXISTS batting_stats CASCADE')
    op.execute('DROP TABLE IF EXISTS fielding_stats CASCADE')
    op.execute('DROP TABLE IF EXISTS games CASCADE')
    op.execute('DROP TABLE IF EXISTS pitches CASCADE')
    op.execute('DROP TABLE IF EXISTS pitching_stats CASCADE')
    op.execute('DROP TABLE IF EXISTS player_bio CASCADE')
    op.execute('DROP TABLE IF EXISTS player_game_grades CASCADE')
    op.execute('DROP TABLE IF EXISTS stat_rows CASCADE')
    op.execute('DROP TABLE IF EXISTS stat_tables CASCADE')
    op.execute('DROP TABLE IF EXISTS teams CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atbats', sa.Column('id', sa.Integer, primary_key=True))
    op.create_table('batting_stats', sa.Column('id', sa.Integer, primary_key=True))
    op.create_table('fielding_stats', sa.Column('id', sa.Integer, primary_key=True))
    op.create_table('games', sa.Column('id', sa.Integer, primary_key=True))
    op.create_table('pitches', sa.Column('id', sa.Integer, primary_key=True))
    op.create_table('pitching_stats', sa.Column('id', sa.Integer, primary_key=True))
    op.create_table('player_bio', sa.Column('id', sa.Integer, primary_key=True))
    op.create_table('player_game_grades', sa.Column('id', sa.Integer, primary_key=True))
    op.create_table('stat_rows', sa.Column('id', sa.Integer, primary_key=True))
    op.create_table('stat_tables', sa.Column('id', sa.Integer, primary_key=True))
    op.create_table('teams', sa.Column('id', sa.Integer, primary_key=True))
    # ### end Alembic commands ###
